DROP TABLE IF EXISTS logs;

CREATE TABLE logs (
  log_id INT AUTO_INCREMENT  PRIMARY KEY,
  url VARCHAR(250) NOT NULL,
  date_time TIMESTAMP NOT NULL,
  request_type VARCHAR(250) DEFAULT NULL,
  resource_url VARCHAR(250) DEFAULT NULL,
  status INTEGER DEFAULT NULL
);